# Use a versão estável do Node.js
FROM node:14

# Define o diretório de trabalho no container
WORKDIR /usr/src/app

# Copia o arquivo package.json para o diretório de trabalho
COPY package.json .

# Instala apenas as dependências necessárias
RUN npm install --omit=dev


# Copia o restante do código para o container
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Define o comando padrão para iniciar a aplicação
CMD ["npm", "start"]
