version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/myapi
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
      